---
title: "n9605100-project"
author: "Xiaoran Chu"
---
#Task 1: Data Mining

##Read Data
```{r}
#get working directory
wd<-getwd()
#set working directory
setwd(wd)
#read yeast data from working directory
yeast <-read.table("./yeast.data", sep = "", header = FALSE)
#Change the column name of the dataset to those provided by the lecturer
names(yeast) <- c("Sequence.Name", "mcg","gvh","alm","mit","erl","pox","vac","nuc","Localisation.Site")
```

##70/30

###Split Data
```{r}
#Generate random data
set.seed(1234)
#split data into 70% 30%
sep1 <- sample(2, nrow(yeast), replace=TRUE, prob=c(0.7, 0.3))
train_data1 <- yeast[sep1==1,]
test_data1 <- yeast[sep1==2,]
```

###Prediction
```{r}
#Load party, the pacakge for partitioning
library(party)
#set the formula
formula <-Localisation.Site~mcg+gvh+alm+mit+erl+pox+vac+nuc
#set training data
yeast_ctree1<-ctree(formula, data=train_data1)
#prediction
table(predict(yeast_ctree1, newdata = test_data1), test_data1$Localisation.Site)
```
###Confusion Matrix
```{r}
#load caret, the package for classification and regression training
library(caret)
#confusion matrix
con1<-confusionMatrix(predict(yeast_ctree1, newdata = test_data1), test_data1$Localisation.Site)
con1
```
##80/20
```{r}
#generate random data
set.seed(1234)
#split data into 80% 20%
sep2 <- sample(2, nrow(yeast), replace=TRUE, prob=c(0.8, 0.2))
train_data2 <- yeast[sep2==1,]
test_data2 <- yeast[sep2==2,] 
```

###Prediction 
```{r}
#set training data
yeast_ctree2<-ctree(formula, data=train_data2)
#prediction
table(predict(yeast_ctree2, newdata = test_data2), test_data2$Localisation.Site)
```
###Confusion Matrix
```{r}
#confusion matrix
con2<-confusionMatrix(predict(yeast_ctree2, newdata = test_data2), test_data2$Localisation.Site)
con2
```

#Task 2: Visualisation

##Plot(70/30)
```{r, fig.width=40, fig.height=12}
plot(yeast_ctree1)
```
##Plot(80/20)
```{r, fig.width=40, fig.height=12}
plot(yeast_ctree2)
```

##Heatmap(70/30)
```{r}
#convert result of confusion matrix (class) into data frame
n1<-as.data.frame(con1$table)
#normalize the Frequency of n1 to between 0 and 1 by using min-max normalization
n1$min.max<-(n1$Freq-min(n1$Freq))/(max(n1$Freq)-min(n1$Freq))*(1-0)+0
n1$z.score<-(n1$Freq-mean(n1$Freq))/sd(n1$Freq)
max(n1$Freq)
n1$d.scale<-n1$Freq/100
#rename the column
names(n1)<-c("Prediction","Reference","Frequency","min.max")
```

```{r}
library(ggplot2)
library(reshape2)
#reverse the order of y axis (Prediction)
n1$Prediction<-with(n1,factor(Prediction,levels = rev(levels(Prediction))))
#Plot the data
ggplot(aes(Reference, Prediction), data=n1)+geom_tile(aes(fill=min.max), color="White",data=n1)+scale_fill_gradient(low="white",high="firebrick1")+ggtitle(label = "Confusion Matrix Heatmap(70/30)")+theme_minimal()+theme(plot.title = element_text(hjust = 0.5, lineheight = 0.8, face = "bold"))+xlab("Reference")+scale_x_discrete(position = "top")
```

##Heatmap(80/20)
```{r}
#convert result of confusion matrix (class) into data frame
n2<-as.data.frame(con2$table)
#normalize the Frequency of n2 to between 0 and 1 by using min-max normalization
n2$min.max<-(n2$Freq-min(n2$Freq))/(max(n2$Freq)-min(n2$Freq))*(1-0)+0
#rename the column
names(n2)<-c("Prediction","Reference","Frequency","min.max")
```


```{r}
#reverse the order of y axis (Prediction)
n2$Prediction<-with(n2,factor(Prediction,levels = rev(levels(Prediction))))
#Plot the data
ggplot(aes(Reference, Prediction), data=n2)+geom_tile(aes(fill=min.max), color="White",data=n2)+scale_fill_gradient(low="white",high="limegreen")+ggtitle(label = "Confusion Matrix Heatmap(80/20)")+theme_minimal()+theme(plot.title = element_text(hjust = 0.5, lineheight = 0.8, face = "bold"))+xlab("Reference")+scale_x_discrete(position = "top")
```

#Task 3: Data Analysis
(to be continued)